### PR TITLE
Fix authentication failed

### PR DESCRIPTION
**Pull request by ClemPi**
This fix `Tspi_NV_WriteValue failed: 0x00000001 - layer=tpm, code=0001 (1), Authentication failed`

This address #2

### CODE REVIEW

**Comment by morbitzer** [comment]
Looks good. pull request #6 includes something similar (adding `tpm_nvwrite -i $INDEX -f $KEYFILE -z -p$OWNERPW`), but this might work even better in some scenarios.

**Comment by dirkjanm** [comment]
Seems there are some merge conflicts because of #6 now, I'll leave it up to @morbitzer to figure out which one is best :)

**Comment by ClemPi** [comment]
I think the best is to incorporate my little change in #6 and close this one.

**Comment by dirkjanm** [comment]
Managed to fix it :) Thanks for the contributions!

**Pull request merged**
